default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: volunteers_development

test:
  <<: *default
  database: volunteers_test

production:
  <<: *default
  database: volunteers_production
  username: volunteers
  password: <%= ENV['CLEAN_DATABASE_PASSWORD'] %>
